# internal-gateway.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal  # This must match your Helm release label
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "weather.internal.local"
    - "advisor.internal.local"
