# Code Generated by Sidekick is for learning and experimentation purposes only.

variable "prometheus_release_name" {
  description = "The name of the Helm release"
  type        = string
}

variable "prometheus_namespace" {
  description = "The namespace to deploy the Helm release"
  type        = string
}

variable "prometheus_chart_version" { # Renamed from "version"
  description = "The version of the Helm chart"
  type        = string
}

variable "prometheus_repository" {
  description = "The Helm repository URL"
  type        = string
}

variable "prometheus_chart_name" {
  description = "The name of the Helm chart"
  type        = string
}

variable "prometheus_create_namespace" {
  description = "Flag to create the namespace"
  type        = bool
}

variable "prometheus_scrape_interval" {
  description = "The scrape interval for Prometheus"
  type        = string
  default     = "15s"
}

variable "prometheus_evaluation_interval" {
  description = "The evaluation interval for Prometheus"
  type        = string
  default     = "15s"
}

variable "prometheus_scrape_timeout" {
  description = "The scrape timeout for Prometheus"
  type        = string
  default     = "10s"
}