name: Tofu destroy

on:
  workflow_dispatch:

jobs:
  Tofu-destory:
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1 
        with:
          tofu_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ap-south-1
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
    
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Initialise the tofu provider
        run: tofu init

      - name: tofu destroy resource
        run: tofu destroy --auto-approve 
