name: Terraform lint

on:
    pull_request:
        branches: [ main ]

jobs:
    tofu-lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: tofu-lint
            uses: terraform-linters/setup-tflint@v5
            with:
                tflint_version: latest
          - id: tflint
            run: tflint -f compact
            continue-on-error: true



